#!/usr/bin/env bash
# Script that configure HAproxy on your lb-01 server.

apt-get update
apt-get install -y haproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.default
echo "
listen 19018-lb-01
        bind *:80
        mode http
        balance roundrobin
        option httpclose
        option forwardfor
        server 22487-web-01 44.211.26.34 check
        server 22487-web-02 44.192.114.202 check
" >> /etc/haproxy/haproxy.cfg
service haproxy restart
